services:
  post:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=software
      - POSTGRES_DB=avar
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgres/data
    networks:
      - spring-boot-network
  spring-boot-app:
    container_name: spring-demo
    image: spring/demo
    build: 
     dockerfile: Dockerfile	
    depends_on: 
      - post
    ports:
      - "8080:8080"
    networks:
      - spring-boot-network
volumes: 
  postgres:
  
networks:
  spring-boot-network:
   driver: "bridge"